export const EredivisieTeams = [
    {
        title: "Ajax",
        description: "AFC Ajax — Amsterdam based football club",
        review: 9,
        loc: { type: "Point", coordinates: [4.941, 52.314] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_AFC_Ajax_(1928-1991,_2025-).png?width=512",
        hasBookmark: false,
    },
    {
        title: "AZ Alkmaar",
        description: "AZ Alkmaar — North Holland football club",
        review: 8,
        loc: { type: "Point", coordinates: [4.741915, 52.612769] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/AZ_Alkmaar.png?width=512",
        hasBookmark: false,
    },
    {
        title: "Excelsior",
        description: "SBV Excelsior — Rotterdam based club",
        review: 7,
        loc: { type: "Point", coordinates: [4.520370, 51.917090] },
        imageUrl: "https://excelsiorrotterdam.nl/wp-content/uploads/2021/07/Excelsior-Rotterdam-rgb.png",
        hasBookmark: false,
    },
    {
        title: "FC Groningen",
        description: "Football Club Groningen — Groningen based club",
        review: 7,
        loc: { type: "Point", coordinates: [6.591645, 53.206182] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/FC_Groningen_logo.png?width=512",
        hasBookmark: false,
    },
    {
        title: "FC Twente",
        description: "FC Twente — Enschede based club",
        review: 8,
        loc: { type: "Point", coordinates: [6.838045, 52.236679] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/FC_Twente.png?width=512",
        hasBookmark: false,
    },
    {
        title: "FC Utrecht",
        description: "FC Utrecht — Utrecht based football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.145922, 52.078512] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/92/FC_Utrecht.png",
        hasBookmark: false,
    },
    {
        title: "FC Volendam",
        description: "FC Volendam — Volendam football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.066359, 52.494374] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/FC_Volendam_logo.png?width=512",
        hasBookmark: false,
    },
    {
        title: "Feyenoord",
        description: "Feyenoord — Rotterdam football club",
        review: 9,
        loc: { type: "Point", coordinates: [4.523, 51.893] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Feyenoord_logo_since_2024.png?width=512",
        hasBookmark: false,
    },
    {
        title: "Fortuna Sittard",
        description: "Fortuna Sittard — Sittard based club",
        review: 7,
        loc: { type: "Point", coordinates: [5.843419, 50.991860] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Fortuna_Sittard_logo_(PNG).png?width=512",
        hasBookmark: false,
    },
    {
        title: "Go Ahead Eagles",
        description: "Go Ahead Eagles — Deventer football club",
        review: 8,
        loc: { type: "Point", coordinates: [6.172700, 52.260412] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Go_Ahead_Eagles_logo_2015-heden.png?width=512",
        hasBookmark: false,
    },
    {
        title: "Heracles Almelo",
        description: "Heracles Almelo — Almelo football club",
        review: 7,
        loc: { type: "Point", coordinates: [6.650629, 52.338860] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Heracles_Almelo_logo.png?width=512",
        hasBookmark: false,
    },
    {
        title: "NAC Breda",
        description: "NAC Breda — Breda based club",
        review: 7,
        loc: { type: "Point", coordinates: [4.750507, 51.594777] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_NAC_Breda.png?width=512",
        hasBookmark: false,
    },
    {
        title: "NEC Nijmegen",
        description: "NEC — Nijmegen football club",
        review: 7,
        loc: { type: "Point", coordinates: [5.837355, 51.822463] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b4/NEC_Logo.png",
        hasBookmark: false,
    },
    {
        title: "PEC Zwolle",
        description: "PEC Zwolle — Zwolle based club",
        review: 7,
        loc: { type: "Point", coordinates: [6.120734, 52.517207] },
        imageUrl: "https://iconape.com/wp-content/files/tu/89420/png/pec-zwolle.png",
        hasBookmark: false,
    },
    {
        title: "PSV Eindhoven",
        description: "PSV Eindhoven — Eindhoven football club",
        review: 9,
        loc: { type: "Point", coordinates: [5.469, 51.441] },
        imageUrl: "/upload_mm/f/2/e/108043_fullimage_logo-psv2020-240x240.png",
        hasBookmark: false,
    },
    {
        title: "SC Heerenveen",
        description: "SC Heerenveen — Heerenveen based club",
        review: 7,
        loc: { type: "Point", coordinates: [5.936022, 52.958672] },
        imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/SC_Heerenveen_logo.png?width=512",
        hasBookmark: false,
    },
    {
        title: "Sparta Rotterdam",
        description: "Sparta Rotterdam — Rotterdam club",
        review: 7,
        loc: { type: "Point", coordinates: [4.433478, 51.919494] },
        imageUrl: "https://www.cleanpng.com/png-sparta-rotterdam-football-logo-feyenoord-6780086/",
        hasBookmark: false,
    },
    {
        title: "Telstar",
        description: "SC Telstar — Velsen based club",
        review: 6,
        loc: { type: "Point", coordinates: [4.634855, 52.455256] },
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/4/46/SC_Telstar.png",
        hasBookmark: false,
    },
]